

device:
  seed: 0
  cuda: True
  gpu_idx: 0

logger:
  log_dir: '/home/zy/zz/all_logs/offorrl'

env:
  name: 'halfcheetah-medium-v2'
  max_episode_steps: -1 # if >0, will set the max episode length, otherwise follow the default

buffer:
  max_replay_buffer_size: 2000000
  load_buffer: True

rlalg:
  online_finetune: False
  start_epoch: -1000 # offline epochs
  num_epochs: 0 # online epochs
  batch_size: 256
  num_eval_steps_per_epoch: 5000
  num_trains_per_train_loop: 1000
  num_expl_steps_per_train_loop: 1000
  min_num_steps_before_training: 1000 # used at the beginning of online finetune


trainer:
  name: 'CQL'


hydra:
  output_subdir: null

defaults:
  - _self_
  - trainer: iql
  - override hydra/launcher: joblib





